server:
  port: 8081
  servlet:
    context-path: /jobify

spring:
  application:
    name: jobify

jwt:
  secret: mySuperSecretKeyForJobifyApplication1234567890
  expiration: 86400000   # 1 day in ms

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none   # use update only in local dev
    show-sql: false #Make true to see it to solve any issue
    properties:
      hibernate:
        format_sql: true
        #default_schema: "Users"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
